version: '3.1'

services:

  myimage_web:
    build: requirements/nginx/
    depends_on:
      - myimage_wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    container_name: mycontainer_web

  myimage_wordpress:
    build: requirements/wordpress/
    env_file: .env
    restart: always
    depends_on:
      - myimage_db
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    container_name: mycontainer_wordpress

  myimage_db:
    build: requirements/mariadb/
    env_file: .env
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception_net
    container_name: mycontainer_db

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jgarlic/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/jgarlic/data/db

networks:
  inception_net:
    name: inception_net
    driver: bridge
